### ISSUE TITLE
Cloning the element duplicates the content of a component in certain conditions

### ISSUE THREAD

**Issue by priandsf** [ionic-team/stencil#1070]
**Stencil version:**

```
 @stencil/core@0.12.4
```

**I'm submitting a:**

[X ] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
When a component is *not* using shadow dom, JQuery.clone() creates a component with the content duplicated (the content appears twice). The issue does not exists when Shadow DOM is true, or with the regular DOM cloneNode()

**Expected behavior:**
The content should not be duplicated

**Steps to reproduce:**
- Create a new Stencil project using the component starter project (https://github.com/ionic-team/stencil-component-starter).
- Replace index.html with the code bellow
- The page shows 2 buttons: "DOM Clone" & "JQuery Clone". A click on each of them properly clones the component
- edit my-component.tsx and set shadow to false
- Now the "JQuery Clone" creates a component with its content added twice while "DOM Clone" still works as it should. 

Even the bug is specific to JQuery.clone(), it might reveal a sequence of events that is not properly handled by the Stencil runtime and leads to this duplicated body.

**Related code:**

```
<!DOCTYPE html>
<html dir="ltr" lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=5.0">
  <title>JQuery Clone Issue</title>
  <script src="/build/mycomponent.js"></script>

  <script
  src="https://code.jquery.com/jquery-3.3.1.js"
  integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
  crossorigin="anonymous"></script>

</head>
<body>

  <h3>Original component</h3>
  <my-component id="component" first="Stencil" last="'Don't call me a framework' JS"></my-component>

  <br/>
  <button id="button1" onclick="cloneComponent()">DOM Clone</button>
  <button id="button2">jQuery Clone</button>
  <h3>Cloned component</h3>
  <br/>

  <div id="container">
  </div>

  <script>
      function cloneComponent() {
        var c = document.getElementById("component");
        var nc = c.cloneNode();
        document.getElementById("container").append(nc);
      }
      $("#button2").click( function() {
        var c = $("#component")
        var cl = c.clone()
        $("#container").append(cl);
      });
  </script>

</body>
</html>
```

**Other information:**

**Comment by priandsf** [comment]
Actually, the same problem appears with DOM cloneNode(true), when deep cloning (jQuery is always doing that). The whole content is cloned, and re-added when the component is rendered. Is a simple fix to remove any existing children before rendering for the first time?

**Comment by davescottschneider** [comment]
Any movement on this? I'm also experiencing this issue.

**Comment by johannesjo** [comment]
Duplicates #1083

**Comment by xene** [comment]
I'm also experiencing this issue. Any updates on this?

**Comment by johannesjo** [comment]
@xene didn't test it myself, but this will supposedly be fixed with stencil v1

**Comment by xene** [comment]
> @xene didn't test it myself, but this will supposedly be fixed with stencil v1

Where can I find this V1?

**Comment by ckrack** [comment]
This is not fixed with `@stencil/core@1.0.3`.
I've created an example here:
https://github.com/ckrack/stencil-clonenode-bug

**Comment by Sebosek** [comment]
Hello, stencil 1.2.2 still reproducible.
![bug](https://user-images.githubusercontent.com/372542/62103014-6bd05080-b29b-11e9-9a95-076f12577f10.gif)

```
import { Component, h } from '@stencil/core';

@Component({
  tag: 'bug-component',
  scoped: true,
})
export class Bug {
  render() {
    return (
      <span>🐛</span>
    )
  }
}
```

```
<bug-component
  id="source"
></bug-component>
<button
  id="clone"
>Clone the bug</button>

<div id="canvas">
</div>

<script>
  document.getElementById('clone').addEventListener('click', () => {
    const el = document.getElementById('source');
    const clone = el.cloneNode(true);

    el.insertAdjacentElement('afterend', clone);
    document.getElementById('canvas').appendChild(clone);
  });
</script>
```

**Comment by denniswiemer** [comment]
Same kind of behaviour is visible in AngularJS apps with Stenciljs V1.x. As soon as a Stencil component is within ng-if, switch, loop etc and digest cycle triggers again. The inner content of the stencil component is rendered twice, or in other words, the first rendered html is not cleaned up as it seems.

When using Stenciljs v0.18.0 I don't see the issue occurring
