### ISSUE TITLE
V1.9.0-18 Unit & e2e tests warning messages

### ISSUE THREAD

**Issue by jepiqueau** [ionic-team/stencil#2210]
@adamdbradley 
Following your request for more testing

**Stencil version:**

```
 @stencil/core@1.9.0-18
```

**I'm submitting a:**

[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**
Going from V1.8.7 to V1.9.0-18 and using --next when building my component library, everything works fine for me except two things:
 - when running ```npm run test.spec``` i got for some components, not all 
     ```console.warn node_modules/@stencil/core/internal/testing/index.js:237
      Use newSpecPage() to instanciate component instances. ```
 - when running ```npm run test.e2e``` i got for each component  the following message
    ```console.error node_modules/@stencil/core/testing/index.js:36945
      Failed to load resource: the server responded with a status of 404 (Not Found) 
      Location: http://localhost:3333/build/jeep.css``` 
but all the tests (unit & e2e) run successfully
**Expected behavior:**
<!-- Describe what the behavior would be without the bug. -->
As the runs complete successfully, they should not be warning message 
i have tried to add a global css as we do for PWA but it doesn't help, 
if after the build, you add an empty jeep.css in the www dir, the message when running the e2e test disappear.
For the unit test message, it is related to the Host element, but i couldn't figure out the differences between my components 
**Steps to reproduce:**
<!-- If you are able to illustrate the bug or feature request with an example, please provide steps to reproduce and if possible a demo
-->

**Related code:**
 see on github 
```
https://github.com/jepiqueau/jeepnext
``` 

**Other information:**
<!-- List any other information that is relevant to your issue. Stack traces, related issues, suggestions on how to fix, Stack Overflow links, forum links, etc. -->
see my message of today (Friday 21) on Slack Technical-Questions Channel and the dialog with @simonhaenisch

**Comment by adamdbradley** [comment]
Thanks for creating the issue and providing a repo case! Should be fixed in next release, thanks

**Comment by trazek** [comment]
I have also noticed this message 

> Use newSpecPage() to instanciate component instances

even for unit tests which only test component class functionality. Can we expect this warning to be removed for this case as well?

Also, should be "instantiate"

**Comment by jepiqueau** [comment]
@trazek  as you can see @adamdbradley  has closed issue so update to 1.9.2

**Comment by WickyNilliams** [comment]
I'm still getting this issue even with 1.9.2 - specifically in e2e tests:

```
console.error node_modules/@stencil/core/testing/index.js:32943
    Failed to load resource: the server responded with a status of 404 (Not Found) 
    Location: http://localhost:3333/build/duet.css

  console.error node_modules/@stencil/core/testing/index.js:32766
    requestfailed http://localhost:3333/build/duet.css
```

This is annoying as it outputs so much that it fills my terminal buffer. However the tests still pass

**Comment by trazek** [comment]
It seems like this is what Stencil wants us to do now when unit testing: 

https://github.com/ionic-team/stencil/issues/2275

Using the `rootInstance` property will get us the class instance essentially.

**Comment by WickyNilliams** [comment]
@trazek doesn't look like that solves the CSS issue in e2e tests though

**Comment by jepiqueau** [comment]
@WickyNilliams try to delete the .stencil, dist, loader, node-modules, www folders and the package-lock.json. in your package.json file keep only    "@stencil/core": "^1.9.2" in the "devDependencies"
and run npm install and npm run test. after this in the package.json file 
```   "devDependencies": {
    "@stencil/core": "^1.9.2",
    "@types/jest": "24.0.20",
    "@types/puppeteer": "1.19.0",
    "jest": "24.9.0",
    "jest-cli": "24.9.0",
    "puppeteer": "2.1.0"
  },
``` this is what i got and the e2e tests work fine

**Comment by jepiqueau** [comment]
@WickyNilliams  in the e2e file i use the following to define some css in the beforeEach function
```
      page = await newE2EPage();
      await page.setViewport({width:800,height:600});
      await page.setContent('<jeep-linechart></jeep-linechart>');
      element = await page.find('jeep-linechart');
      await page.addStyleTag({content: `
      :root {
        --chart-axis-color:#000000;   
      }
      body {position:fixed;margin:0;padding:0;
        overflow:hidden;width:800px;height:600px}
      jeep-linechart {--height:450px;--width:720px;
        --top:50px;--left:40px;--background-color: #f4f9aa;}`
      });

``` 
tell me if it help

**Comment by WickyNilliams** [comment]
I tried deleting everything and doing a fresh install, and am still seeing the errors in the console. I've narrowed it down to these lines https://github.com/ionic-team/stencil/blob/63595bc540db9aa85295f5a8dc8738beb2a37611/src/testing/puppeteer/puppeteer-page.ts#L218-L220

Is there any reason why my stencil build is not outputting this file (assuming it's meant to be there)? Or is there any way to prevent stencil from attempting to load it (since i don't seem to need it for tests)?

**Comment by simonhaenisch** [comment]
`<namespace>.css` is the compilation result of your `globalStyle`, which should be generated under `www/build/<namespace>.css`, and that's what `appStyleUrl` should be. Can you check `appStyleUrl`? Either inspect the page with devtools, or
```
$EDITOR node_modules/@stencil/core/testing/index.js
```
and then search for `typeof appStyleUrl === 'string'` and add a console log.

**Comment by WickyNilliams** [comment]
For now, i just decided to remove the `globalStyle` from our config, as we're injecting the same scss file as a global through other means. Thanks anyway!
