### ISSUE TITLE
Bundling warning SOURCEMAP_ERROR

### ISSUE THREAD

**Issue by dgonzalezr** [ionic-team/stencil#3165]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/stencil/blob/main/.github/CONTRIBUTING.md).
- [X] I agree to follow the [Code of Conduct](https://github.com/ionic-team/stencil/blob/main/CODE_OF_CONDUCT.md).
- [X] I have searched for [existing issues](https://github.com/ionic-team/stencil/issues) that already report this problem, without success.

### Stencil Version

2.11.0

### Current Behavior

When enabling source maps on `stencil.config.ts` a warning message is shown during the build:

![CleanShot 2021-12-01 at 20 09 40](https://user-images.githubusercontent.com/328492/144289783-089b676b-6228-44eb-ab8b-6302d1920e78.png)

### Expected Behavior

Source maps get built without issues.

### Steps to Reproduce

1. Setup a stencil component project.
2. Enable source maps on `stencil.config.ts`: `sourceMap: true`.
3. Build the project with `npm run build`.

### Code Reproduction URL

https://github.com/dgonzalezr/stencil-tailwind

**Comment by rwaskiewicz** [comment]
Looks like this was introduced in v2.10.0, but is not present in v2.9.0. We'll take a further look!

**Comment by dgonzalezr** [comment]
Any update about this issue? It is still happening with the latest @stencil/core version 😐

**Comment by rwaskiewicz** [comment]
I did some preliminary digging on this issue. It appears to:

- occur in v2.9.0 (which is the opposite of what I mentioned [here](https://github.com/ionic-team/stencil/issues/3165#issuecomment-983958568))
- manifest only when more than one output target is used (e.g. `www` and `dist-custom-elements`)

This leads me to believe that rollup is either reading a file that's not in a 'good state' (because it's being modified by another output target) or something similar.  I don't have a definitive timeline for when we'll be able to fix this, but I promise it hasn't been forgotten about 🙂

**Comment by pratheeshp007** [comment]
is there any workaround for this issue?

**Comment by jepiqueau** [comment]
@dgonzalezr @pratheeshp007 This seems to have been fixed in 2.18.0. I update jeep-sqlite this morning with 2.18.0 and the  warning message disappears.

**Comment by jepiqueau** [comment]
@dgonzalezr @pratheeshp007 @rwaskiewicz  Well in fact after having done a npm start when you do a npm run build the warning message is still there

**Comment by KevinCarnaille2** [comment]
Hello there, 
I had the issue for a while and indeed, I'm using multiple output targets.

Fixed the issue by removing the `dist-hydrate-script` output (https://stenciljs.com/docs/hydrate-app#how-to-use-the-hydrate-app)

I don't use it, it was it was a simple experimentation :)

**Comment by KevinCarnaille2** [comment]
Don't know if it can help, my 2 cents : 

I got the warning as soon as I include the `dist-custom-element ` in `outputTarget`. I have no warning if I remove `dist-hydrate-script` as well.
Currently I work with this config : 

```
outputTargets: [
{
    type: 'dist-hydrate-script',
},
{
    type: 'dist',
    dir: './dist',
    copy: [
        { src: 'fonts', dest: './fonts' }
    ]
},
{
    type: 'dist-custom-elements',
    dir: './dist/components'
},
{
    type: 'www',
    empty: false, // to prevent playground compiled css (by sass CLI) to be overriden
    serviceWorker: null, // disable service workers,
    copy: [
        { src: 'fonts', dest: './build/fonts' }
    ]
},
{
    type: 'stats',
    file: './dist/stats.json',
},
{
    type: 'docs-vscode',
    file: './dist/vscode-data.json',
},
```

**Comment by iraklisg** [comment]
> Looks like this was introduced in v2.10.0, but is not present in v2.9.0. We'll take a further look!

Is still present in Stencil 3.1.0

Is there a roadmap on when this will be fixed?

**Comment by rwaskiewicz** [comment]
A dev build of Stencil, `3.2.0-dev.1679942506.7994efe` has been published to npm to fix this issue. Feedback from anyone who can install and test this build out would be much appreciated!

```
npm install @stencil/core@3.2.0-dev.1679942506.7994efe
```

**Comment by rwaskiewicz** [comment]
The fix for this issue has been released in Stencil v3.2.1 this afternoon. As a result, I'm going to close this issue. Should it reappear, please feel free to open a new ticket. Thanks!

**Comment by dgonzalezr** [comment]
@rwaskiewicz Unfortunately after updating `@stencil/core` the issue still remains on my side.

![CleanShot 2023-04-11 at 19 59 54](https://user-images.githubusercontent.com/328492/231236227-b7b35127-10b3-446c-a963-d7405c34b784.png)

You can check the specific branch of this PR:
https://github.com/Endava/bee-q/pull/145

Now, is true that I have multiple outputs configured on my stencil.config.js, so I wonder if the root cause could be another output different from `dist-custom-elements`.

**Comment by dgonzalezr** [comment]
@rwaskiewicz thank you for your reply. I can confirm that removing `dist-hydrate-script` makes the error to disappear 🙂 

![CleanShot 2023-04-12 at 20 10 01](https://user-images.githubusercontent.com/328492/231532374-1edd60b9-3f2c-47e4-94ae-ab26d1e3cad0.png)

**Comment by rwaskiewicz** [comment]
@dgonzalezr Thanks! I'm going to create a new issue here in GitHub to capture the issue with `dist-hydrate-script'

**Comment by shtolcers** [comment]
> @rwaskiewicz thank you for your reply. I can confirm that removing `dist-hydrate-script` makes the error to disappear slightly_smiling_face
> 
> ![CleanShot 2023-04-12 at 20 10 01](https://user-images.githubusercontent.com/328492/231532374-1edd60b9-3f2c-47e4-94ae-ab26d1e3cad0.png)



The same bug can be observed if we set `externalRuntime: false` for this output target.
![Screenshot from 2023-05-16 17-50-30](https://github.com/ionic-team/stencil/assets/7253711/797e9035-b0ce-4712-94d0-3efd7f93a2d5)

**Comment by rwaskiewicz** [comment]
For anyone running into this issue with `dist-custom-elements` and `dist-hydrate-script` set, please see https://github.com/ionic-team/stencil/issues/4260#issuecomment-1613190360

**Comment by rwaskiewicz** [comment]
@shtolcers If you get a moment, can you please try 
```
npm i @stencil/core@4.0.1-dev.1688059870.bea1aeb
```
and help me confirm that fixes the issue?

**Comment by KevinCarnaille2** [comment]
Hi @rwaskiewicz 
I still have the warning in 3.3.0, but I've tried the `4.0.1-dev.1688059870.bea1aeb` and it's fixed !

**Comment by dgonzalezr** [comment]
Hello @rwaskiewicz my apologies for the late response here.

I can confirm that the issue is fixed within the `4.0.1-dev.1688059870.bea1aeb` version

![image](https://github.com/ionic-team/stencil/assets/328492/a65cfa0e-035f-4caa-a91a-da5d9b8fdfe5)

![CleanShot 2023-07-05 at 19 31 07](https://github.com/ionic-team/stencil/assets/328492/50908d3c-42cb-4234-bbd7-a2e67d06bf07)

Thank you so much 🙌🏼
