### ISSUE TITLE
package.json "types" file does not exist:

### ISSUE THREAD

**Issue by Scyks** [ionic-team/stencil#604]
**Stencil version:**
```
 @stencil/core@0.6.7 and upwards
```

**I'm submitting a:**
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://forum.ionicframework.com/ or https://stencil-worldwide.slack.com

**Current behavior:**
Running a stencil build on linux fails with error "the file `dist/types/components.d.ts` is not generated."
```
...
11:25:07 INFO - [25:07.8]  writeBuildFiles started ...
11:25:07 INFO - [25:07.8]  copy assets MEM: 302.4MB
11:25:07 INFO - [25:07.8]  copy styles MEM: 302.4MB
11:25:07 INFO - [25:07.9]  in-memory-fs: data length: 499 MEM: 303.2MB
11:25:07 INFO - [25:07.9]  cache: data length: 51 MEM: 303.2MB
11:25:07 INFO - [25:07.9]  writeBuildFiles finished, files wrote: 119 in 38 ms
11:25:07 INFO - 
11:25:07 INFO - [ ERROR ]  package.json error
11:25:07 INFO -            package.json "types" file does not exist:
11:25:07 INFO -            /.../gen/out/module/dist/types/components.d.ts
11:25:07 INFO - 
11:25:07 INFO - [25:07.9]  build failed in 11.74 s
...
```

**Expected behavior:**
Successful build - which works on stencil/core@0.6.6

**Steps to reproduce:**
node_modules/.bin/stencil build --prerender

**Other information:**
It successfully works with version 0.6.6

**Comment by jgw96** [comment]
Hey! What starter are you using? The app starter or component starter?

**Comment by Scyks** [comment]
We used the App-Starter several month ago.

**Comment by jgw96** [comment]
Ahh ok, things have changed since then, you should not need that types entry anymore https://github.com/ionic-team/stencil-app-starter/blob/master/package.json. Can you update your package.json to match that one? That should fix the issue for you. Thanks!

**Comment by Scyks** [comment]
I removed the properties and try to build our package again. Sadly it doesn't work as you suggested.

```
[ ERROR ]  package.json error
           package.json "main" property is required when generating a distribution and must be set to:
           dist/fioriatoms.js

[ ERROR ]  package.json error
           package.json "types" property is required when generating a distribution. Recommended entry d.ts file is:
           dist/types/components.d.ts

[ ERROR ]  package.json error
           package.json "collection" property is required when generating a distribution and must be set to:
           dist/collection/collection-manifest.json
```

Package.json
```
{
  "name": "@atoms/core",
  "namespace": "...",
  "version": "0.0.1",
  "description": "...",
  "scripts": {
    "build": "stencil build --prerender --debug"
  },
  "files": [
    "dist/"
  ],
  "dependencies": {},
  "devDependencies": {
    "@stencil/core": "0.6.18",
    "@stencil/dev-server": "0.0.18",
    "@stencil/sass": "0.0.3",
    "@stencil/utils": "0.0.4",
    "@types/jest": "^22.1.2",
    "jest": "^22.2.2",
    "jsonfile": "^4.0.0",
    "shelljs": "^0.8.1"
  },
  "repository": {
    "type": "git",
    "url": "..."
  },
  "author": "...",
  "license": "UNLICENSED",
  "bugs": {
    "url": "..."
  },
  "homepage": "..."
}

```

**Comment by RecuencoJones** [comment]
I just experienced this same issue with `@stencil/core@0.6.18`.

My `package.json` `types` property was pointing to `dist/types/components.d.ts`, and `stencil build` failed due to

```
[ ERROR ]  package.json error
           package.json "types" file does not exist:
           /.../dist/types/components.d.ts
```

Looks like this file is not generated anymore in `dist/types`.
Also, removing `types` entry from `package.json` did not fix it for me.

Since we are only exporting one component (let it be `foo`), changing `types` entry to `dist/types/components/foo/foo.d.ts` fixed it.

**Comment by adamdbradley** [comment]
Yes the location of the types changed in that version. If you're only generating a website you do not need to generate the distribution too, so I'd recommend removing that config. Thanks
