### ISSUE TITLE
Ionic submit button should trigger form submission

### ISSUE THREAD

**Issue by DavidFrahm** [ionic-team/stencil#967]
**Stencil version:**

```
@stencil/core@0.10.10
```

**I'm submitting a:**

[x] bug report
[ ] feature request
[ ] support request => Please do not submit support requests here, use one of these channels: https://stencil-worldwide.herokuapp.com/ or https://forum.ionicframework.com/

**Current behavior:**

When using ionic button `<ion-button type="submit">` to submit form, clicking that button results in a full page refresh with the form query params in the url.

**Expected behavior:**

Clicking the Ionic submit button should trigger the normal form submission (e.g, `onSubmit()`). This is the same behavior when using non-Ionic submit button (i.e., `<input type=""submit">`).

**Steps to reproduce:**

**Related code:**

```tsx
// insert any relevant code here
```

**Other information:**

**Comment by adamdbradley** [comment]
Fixed https://github.com/ionic-team/ionic/commit/c05d672703c361e287ef6252a721db17f869c37e

thanks for the report!

**Comment by DavidFrahm** [comment]
@adamdbradley Thanks for the attention on this, however I'm not sure its fixed for stencil non-angular projects.

In my non-angular project, a straight clone from ionic-pwa-toolkit with just one form added on the home page, my form still exhibits the same behavior -- reloads the page with query params instead of the desired behavior of only submitting the form.

I updated my dependencies:

```
 "dependencies": {
    "@ionic/core": "^4.0.0-beta.2",
    "@stencil/core": "^0.11.3"
  },
 ```

Anything I'm doing wrong here? Hope I'm not bothering you unnecessarily ;)

**Comment by DavidFrahm** [comment]
Another use case for this: to DRY out code for forms where you need to submit the form whether user:

- Presses ENTER key in an input field
- Clicks submit button

Right now, to accomplish this you need to:

- Implement form onSubmit() code, to submit via the ENTER key
- Implement ion-button onClick() code, to submit via user clicking a button

**Comment by DavidFrahm** [comment]
The fix at https://github.com/ionic-team/ionic/commit/c05d672703c361e287ef6252a721db17f869c37e sure looks like it would work. And in the [test form html](https://github.com/ionic-team/ionic/blob/master/core/src/components/button/test/form/index.html) it does -- but in a Stencil (non-angular) app it doesn't.

**Comment by joewoodhouse** [comment]
Agree, this still doesn't seem to be working in non-angular projects.
